### ISSUE TITLE
Error while building the Joynr Docker image(MoC0Crw)

### ISSUE THREAD

**Issue by JaehoonLeee** [bmwcarit/joynr#20] opened 2018-02-26 02:21 UTC
Hi all,

I am following the tutorials, and on one of the first steps to build the Joynr Docker image the following error occurs:

 sudo docker run --rm --sig-proxy -e DEV_UID="$(id -u)" \
>     -v /home/jaehoon88.lee/joynr_master/joynr:/data/src \
>     -v /usr/share/maven:/home/joynr/.m2 \
>     -v /home/jaehoon88.lee/joynr_master/joynr/build:/data/build \
>     joynr-cpp-gcc \
>     /data/src/docker/joynr-cpp-base/scripts/build/cpp-clean-build.sh --jobs 4
useradd: warning: the home directory already exists.
Not copying any file from skel directory into it.

========================================
= CPP CLEAN BUILD GCOV: OFF JOBS: 4
========================================

========================================
= Enable core dumps
========================================

========================================
= ENVIRONMENT
========================================

HOSTNAME=a45d880b051f
INSTALL_DIR=/data/install
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/payara41/glassfish/bin
SRC_DIR=/data/src
REFRESHED_AT=2017-02-13
PWD=/home/joynr
FGC=f24
SHLVL=2
HOME=/home/joynr
DEV_UID=1033
TINI_VERSION=v0.13.1
DISTTAG=f24docker
BUILD_DIR=/data/build
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig::/usr/local/lib64/pkgconfig
GOSU_VERSION=1.3
_=/usr/bin/env
ADDITIONAL_CMAKE_ARGS is

========================================
= CLEAN BUILD DIRECTORY
========================================

+ cmake -DENABLE_GCOV=OFF -DPYTHON_EXECUTABLE=/usr/bin/python -DJOYNR_SERVER=localhost:8080 -DCMAKE_BUILD_TYPE=Debug -DENABLE_CLANG_FORMATTER=ON -DBUILD_TESTS=ON -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_PREFIX=/usr -DJOYNR_ENABLE_ACCESS_CONTROL:BOOL=ON /data/src/cpp

========================================
= RUN CMAKE
========================================

-- The C compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- variable CMAKE_MODULE_PATH=/data/src/cpp/CMake
-- variable CMAKE_PREFIX_PATH=
-- variable CMAKE_VERSION=3.9.0
-- variable CMAKE_ROOT=/usr/share/cmake
-- variable CMAKE_SOURCE_DIR=/data/src/cpp
-- variable CMAKE_CURRENT_SOURCE_DIR=/data/src/cpp
-- variable BUILD_PACKAGE_SHLIB=
-- variable BUILD_PACKAGE_BIN=
-- variable BUILD_PACKAGE_DEV=
-- variable BUILD_PACKAGE_LIBRARY=
-- variable BUILD_PACKAGE_TESTS=
-- ----------------- INSTALL LOCATIONS -----------------
-- CMAKE_INSTALL_PREFIX          = /usr
-- CMAKE_INSTALL_BINDIR          = bin
-- INSTALL_TEST_DIR              = bin
-- CMAKE_INSTALL_LIBDIR          = lib64
-- INSTALL_CMAKE_DIR             = lib64/cmake/joynr
-- CMAKE_INSTALL_INCLUDEDIR      = include
-- CMAKE_INSTALL_SYSCONFDIR      = /etc
-- CMAKE_INSTALL_FULL_SYSCONFDIR = /etc
-- JOYNR_INSTALL_FULL_SYSCONFDIR = /etc/joynr
-- -----------------------------------------------------
-- option ENABLE_CCACHE=OFF
-- option GENERATE_SOURCES=OFF
-- option USE_PLATFORM_SPDLOG=ON
-- option USE_PLATFORM_MUESLI=ON
-- option USE_PLATFORM_MOSQUITTO=ON
-- option USE_PLATFORM_GTEST_GMOCK=ON
-- option USE_PLATFORM_WEBSOCKETPP=ON
-- option JOYNR_ENABLE_DLT_LOGGING=OFF
-- option JOYNR_ENABLE_STDOUT_LOGGING=ON
-- option USE_PLATFORM_SMRF=ON
-- option USE_PLATFORM_MOCOCRW=ON
-- option BUILD_TESTS=ON
-- option ENABLE_GCOV=OFF
-- option ENABLE_DOXYGEN=ON
-- option BUILD_CLUSTER_CONTROLLER=ON
-- option BUILD_SHARED_LIBS=ON
-- option ENABLE_CLANG_FORMATTER=ON
-- CLANG_FORMAT_PATH=/usr/local/bin/clang-format
-- option ENABLE_INCLUDE_WHAT_YOU_USE=OFF
-- option ENABLE_CLANG_TIDY=OFF
-- variable JOYNR_SERVER_HOST=localhost
-- variable CMAKE_BUILD_TYPE=Debug
-- variable JOYNR_SERVER_HTTP_PORT=8080
-- variable JOYNR_SERVER_MQTT_PORT=1883
-- variable JOYNR_SERVER_MQTT_TLS_PORT=8883
-- variable JOYNR_BINARY_DIR=/data/build/joynr/bin
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") found components:  doxygen missing components:  dot
-- doxygen DOXYGEN_FOUND=YES
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   chrono
--   date_time
--   atomic
-- variable Boost_FOUND=1
-- variable Boost_INCLUDE_DIRS=/usr/include
-- variable Boost_LIBRARY_DIRS=/usr/lib64
-- variable Boost_LIBRARIES=/usr/lib64/libboost_system.so;/usr/lib64/libboost_filesystem.so;/usr/lib64/libboost_thread.so;/usr/lib64/libboost_chrono.so;/usr/lib64/libboost_date_time.so;/usr/lib64/libboost_atomic.so
-- variable Boost_VERSION=1.60.0
-- ############ Import: cURL ############
-- Found CURL: /usr/lib64/libcurl.so (found version "7.47.1")
-- variable CURL_FOUND=TRUE
-- variable CURL_VERSION_STRING=7.47.1
-- variable CURL_INCLUDE_DIRS=/usr/include
-- variable CURL_LIBRARIES=/usr/lib64/libcurl.so
-- cURL::curl target not defined. Creating IMPORTED target.
-- CMAKE_GENERATOR=Unix Makefiles
-- compiler CMAKE_C_COMPILER=/usr/bin/cc
-- compiler CMAKE_C_COMPILER_ID=GNU
-- compiler CMAKE_C_COMPILER_VERSION=6.3.1
-- compiler CMAKE_CXX_COMPILER=/usr/bin/c++
-- compiler CMAKE_CXX_COMPILER_ID=GNU
-- compiler CMAKE_CXX_COMPILER_VERSION=6.3.1
-- variable spdlog_INCLUDE_DIRS=/usr/local/include/usr/local/include
-- RapidJSON found. Headers: /usr/local/include
-- variable muesli_INCLUDE_DIRECTORIES= /usr/local/include;/usr/local/include;/usr/local/include
CMake Error at CMakeLists.txt:700 (find_package):
  Could not find a package configuration file provided by "MoCOCrW"
  (requested version 0.1.0) with any of the following names:

    MoCOCrWConfig.cmake
    mococrw-config.cmake

  Add the installation prefix of "MoCOCrW" to CMAKE_PREFIX_PATH or set
  "MoCOCrW_DIR" to a directory containing one of the above files.  If
  "MoCOCrW" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!

Could you help me debug this issue? It's really related to my environment or it is something missing in the image configuration?

Thanks and regards.

**Comment by agegov** [comment] 2018-02-26 15:36
Hi JaehoonLeee,

this is a duplicate of https://github.com/bmwcarit/joynr/issues/15, so I will close this issue. Please follow the thread there as we get to this issue. 

Best regards,

**Closed by agegov** 2018-02-26 15:36 UTC
